events {
}
http {
  include /etc/nginx/mime.types;
  index index.html;

  client_max_body_size 0;

  # Server block for the app
  server {
    listen 3000;
    server_name localhost;
    client_max_body_size 0;

    root /usr/share/nginx/html/web-app/;

    location / {
      alias /usr/share/nginx/html/web-app/;
      index index.html;
      try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root /usr/share/nginx/html/web-app/;
    }
  }

  # Server block for the admin
  server {
    listen 3001;
    server_name localhost;
    client_max_body_size 0;

    root /usr/share/nginx/html/admin-app/;
    location / {
      alias /usr/share/nginx/html/admin-app/;
      index index.html;
      try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root /usr/share/nginx/html/admin-app/;
    }
  }
}
