version: '3'

services:
  nx_monorepo_cicd:
    container_name: nx_monorepo_cicd
    # build:
    #   context: ../
    #   dockerfile: Dockerfile
    image: ghcr.io/loinguyen2/nx_monorepo_cicd:latest
    ports:
      - 3000:3000
      - 3001:3001
    restart: always
